version: '2'
services:
    mysql:
      image: mysql:5.7.16
      ports:
       - 3309:3306
      volumes:
       - ./mysql_data:/var/lib/mysql
      environment:
        - TZ=Asia/Shanghai
        - MYSQL_ROOT_PASSWORD=123456
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_buffer_pool_load_at_startup=0 --innodb_buffer_pool_dump_at_shutdown=0
      restart: unless-stopped
    cadvisor:
      image: google/cadvisor:latest
      ports:
        - '8080:8080'
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/ib/docker:ro
        - /dev/disk/:/dev/disk:ro
      restart: unless-stopped
    mysql-exporter:
        image: prom/mysqld-exporter
        ports:
          - '9104:9104'
        environment:
          - DATA_SOURCE_NAME=root:shengdian@(39.100.56.253:12138)/
        restart: always
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        restart: always
        volumes:
          - ~/pro/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
          - '9090:9090'
    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter
        ports:
          - '9100:9100'
    grafana:
        image: grafana/grafana
        volumes:
          - ~/pro/grafana_data:/varlib/grafana
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=pass
        depends_on:
          - prometheus
        ports:
          - '3000:3000'

